### ISSUE TITLE
Build of Devise fails with error in Xcode 6.1.1

### ISSUE THREAD

**Issue by adennen** [netguru/devise-ios#1]
When I build "Devise" from the Devise.xcworkspace file I get the following error message:

devise-ios-master/Devise/DVSUser.m:23:1: @synthesize of 'weak' property is only allowed in ARC or GC mode

**Comment by WojciechTrzasko** [comment]
Hi @adennen.
We are investigating your problem and it looks like configuration error. We will need a little bit more information from you. Did you clone project repository with `--recursive` option?
Like: `git clone --recursive git@github.com:netguru/devise-ios.git`

If not please try running:
`git submodule update --init --recursive`
Next clean the project and install pods.

Please let us know if this solution resolved your problem :)

**Comment by adennen** [comment]
No I'll try that, all I did was download the zip from github and run "pod install" in the root directory

**Comment by adennen** [comment]
After running git clone --recursive https://github.com/netguru/devise-ios.git it is now working, thank you.
I see these instructions listed at the end of the readme.md file and I didn't see it.

Does it make sense to reword the line "git clone --recursive git@github.com:netguru/devise-ios.git" to "git clone --recursive https://github.com/netguru/devise-ios.git" and place it at the top of the readme file for new users?

**Comment by PatrykKaczmarek** [comment]
Hey @adennen 

Thank you for your suggestions. In practice `git clone --recursive git@github.com:netguru/devise-ios.git` makes same job as `https://github.com/netguru/devise-ios.git` so we incline towards default clone `git@...` syntax. We also considered about order in readme file and we believe that presenting features of devise-iOS is more important than the configuration details.
