### ISSUE TITLE
Checking authentication

### ISSUE THREAD

**Issue by jeffleeismyhero** [netguru/devise-ios#3]
I haven't seen a way to test a user's authentication in the demo or documentation for version 0.1.2.

How can I grab the DVSUser object outside of a view controller that inherits from on of the DVS controllers?

**Comment by jeffleeismyhero** [comment]
I should have been clearer in my question above. In my view controller, the following callback fires, but the user object is always empty:

```objective-c
- (void)accountRetrieverViewController:(DVSAccountRetrieverViewController *)controller didSuccessForAction:(DVSRetrieverAction)action user:(DVSUser *)user {
    switch (action) {
        case DVSRetrieverActionLogIn:
        case DVSRetrieverActionSignUp:
            NSLog(@"User: %@", user);
            [self moveToHomeView];
            break;
        case DVSRetrieverActionPasswordRemind:
            [self handlePasswordRemind];
            break;
            
        default:
            break;
    }
}```

```objective-c
2015-03-04 13:54:49.200 Demo[55752:11070958] User: <DVSUser: 0x7b663690, id: (null), sessionToken: (null), email: (null)>
```

**Comment by PatrykKaczmarek** [comment]
Hi @jeffleeismyhero 

We tried to reproduce this issue but with no luck. Are you using demo server url `https://devise-ios-rails-example.herokuapp.com` or your own server? Please let us know and we will investigate issue further.

**Comment by jeffleeismyhero** [comment]
The issue does seem to be related to the backend application. I'm not using the demo server, I'm using this in my own application with Rails 4.2.0 through a fork of devise-ios-rails (see <a href="https://github.com/netguru/devise-ios-rails/pull/1">PR #1</a>).

On that fork for devise-ios-rails, all of the tests pass -- even after updating Rails to 4.2.0 in the spec/dummy application.

**Comment by blase** [comment]
@jeffleeismyhero what exactly is being sent and where? Can you provide us some logs from the Rails app?

**Comment by jeffleeismyhero** [comment]
@blase I've set up an application on Heroku (https://devise-ios-demo.herokuapp.com) that mirrors the pertinent portions from my application. This demo exhibits the same behavior I'm experiencing in my application.

__Rails Log__
```2015-03-06T16:32:17.076153+00:00 heroku[router]: at=info method=POST path="/users/sign_in" host=devise-ios-demo.herokuapp.com request_id=ce0fc96b-80c3-4bab-9641-48462b345610 fwd="68.17.97.152" dyno=web.1 connect=1ms service=109ms status=201 bytes=961```

__Simulator Log__
```2015-03-06 10:32:19.628 Devise Demo[45659:11339701] User: <DVSUser: 0x7a652e30, id: (null), sessionToken: (null), email: (null)>```

The Rails application can be found here: https://github.com/jeffleeismyhero/devise-ios-demo

In the Devise Demo (https://github.com/netguru/devise-ios/tree/master/Devise%20Demo), I've only changed the Server URL and added the ```NSLog(@"%@", user);``` line in:

```objective-c
- (void)accountRetrieverViewController:(DVSAccountRetrieverViewController *)controller didSuccessForAction:(DVSRetrieverAction)action user:(DVSUser *)user {
    switch (action) {
        case DVSRetrieverActionLogIn:
        case DVSRetrieverActionSignUp:
            NSLog(@"User: %@", user);
            [self moveToHomeView];
            break;
            
        case DVSRetrieverActionPasswordRemind:
            [self handlePasswordRemind];
            break;
            
        default:
            break;
    }
}
```

Changing to the project's example Rails application results in success all around.

**Comment by jeffleeismyhero** [comment]
Also, I added some logging to DVSHTTPClient+User.m and this is the response from the Rails application:

```objective-c
2015-03-06 10:53:55.926 Devise Demo[48878:11354857] responseObject: {
    "authentication_token" = "RbjnCBpexKMSANGpeQ_Y";
    "created_at" = "2015-03-06T16:01:34.302Z";
    email = "test@domain.com";
    id = 1;
    "updated_at" = "2015-03-06T16:53:55.964Z";
}
2015-03-06 10:53:55.942 Devise Demo[48878:11354857] User: <DVSUser: 0x7fa4c2416480, id: (null), sessionToken: (null), email: (null)>
```

**Comment by jeffleeismyhero** [comment]
Sorry for so many comments. I believe I've isolated the problem(s).

__1. Parameter Wrapping__
It seems that the response is not formatted with the JSON root. Devise-iOS is expecting:

```
user: {...}
```

but is receiving:

```
{...}
```

Is this something can be added as a configuration option for Devise-iOS? I prefer not to have the JSON root but understand that others may want it.

__2. Lower Camel Case Attributes__
Along the same lines of the JSON root, my parameters are not returned in lowerCamel format. Instead, I'm returning Rails's standard underscore_case format.

Devise-iOS is expecting:

```
{..., authenticationToken: 'abc1234', ...}
```

but is receiving:

```
{..., authentication_token: 'abc1234', ...}
```

**Comment by jeffleeismyhero** [comment]
Please see PR #4. I've added configuration options to allow for these variations in JSON responses. I believe they are pretty common and hope that the changes can be merged in.

**Comment by PatrykKaczmarek** [comment]
Hi @jeffleeismyhero 

Thanks for contributing. We already merged your pull request. I hope this change will solve issue. I close it but feel free to re-open it again if problem will re-appear!
