### ISSUE TITLE
Devise-ios UI

### ISSUE THREAD

**Issue by macsrok** [netguru/devise-ios#6]
This isn't an issue so much as it is a question, as such I feel strange posting it here. I'm sorry.

Do you have to use the provided UI? If not can you provide an example on how to create a devise user object, and send a registration request? 

I have subclassed the DVSUser class.

    class PMOUser: DVSUser, DVSUserPersisting {
    
        func propertiesToPersistByName() -> [AnyObject]! {
            return ["mobile_number", "city", "province", "street_address", "postal_code"]
        }
   
    }

Thanks
Joe

**Comment by rad3ks** [comment]
Hey Joe,

You don't have to use our UI. To register new user:

1. create your user object `PMOUser` and fill it with data,
2. create new `let userManger = DVSUserManager(user: ... )`
3. call `userManager.register(success, failure: failure)`

After registering user you can use `DVSUserManager.defaultManager().user` to access current user (`DVSUser`) instance.

I hope it's helpful and I didn't make any Swift syntax mistake. Feel free to ask further questions or just close the issue :)

Good luck!
