### ISSUE TITLE
[Help Wanted] Response Body in Success block for DVSUserManager loginWithSuccess:failure?

### ISSUE THREAD

**Issue by hedrick** [netguru/devise-ios#9]
Hello,

My route for sign-in returns an expiration date to store locally.

I've looked into DVSUserManager and DVSHTTPClient and cannot find any way to get at the response body for the POST.

Am I missing something in the DVSHTTPClient or DVSUserManager?

**Comment by rad3ks** [comment]
Hello @hedrick 

Thanks for your interest in devise.

I assume you want to use expiration date to force user to authenticate after certain amount of time, am I correct?

This actually can be held by using `sessionToken` in `DVSUser`. If you want to force user to log in again after some time, check if the expiration date, that you keep on your backend service, didn't pass for a given `sessionToken`. It's more safe and you can invalidate users' tokens remotely, anytime you need it.
